### ISSUE TITLE
[Windows10] FormatException: Missing extension byte (at offset 3)   FormatException: Invalid UTF-8 byte (at offset 0)

### ISSUE THREAD

**Issue by nervtech** [osociety/network_tools#114]
I got two errors running on Windows, but the errors don't seem to affect the functionality

```dart
FormatException: Missing extension byte (at offset 3)  error stack：

[        ] FormatException: Missing extension byte (at offset 3)
[        ] #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
[        ] #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
[        ] #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
[        ] #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
[        ] #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
[        ] #5      _rootRunUnary (dart:async/zone.dart:1406:47)
[        ] #6      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
[        ] #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
[        ] #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
[        ] #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[        ] #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
[        ] #11     _StreamController._add (dart:async/stream_controller.dart:648:7)
[        ] #12     _StreamController.add (dart:async/stream_controller.dart:596:5)
[        ] #13     _rootRunUnary (dart:async/zone.dart:1406:47)
[        ] #14     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
[        ] #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
[        ] #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
[        ] #17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[        ] #18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
[        ] #19     _StreamController._add (dart:async/stream_controller.dart:648:7)
[        ] #20     _StreamController.add (dart:async/stream_controller.dart:596:5)
[        ] #21     _Socket._onData (dart:io-patch/socket_patch.dart:2355:41)
[        ] #22     _rootRunUnary (dart:async/zone.dart:1414:13)
[        ] #23     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
[        ] #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
[        ] #25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
[        ] #26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[        ] #27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
[        ] #28     _StreamController._add (dart:async/stream_controller.dart:648:7)
[        ] #29     _StreamController.add (dart:async/stream_controller.dart:596:5)
[        ] #30     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1877:33)
[        ] #31     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1334:14)
[        ] #32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
[        ] #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)



FormatException: Invalid UTF-8 byte (at offset 0) error stack：
[        ] FormatException: Invalid UTF-8 byte (at offset 0)
[        ] #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
[        ] #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
[        ] #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
[        ] #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
[        ] #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
[        ] #5      _rootRunUnary (dart:async/zone.dart:1406:47)
[        ] #6      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
[        ] #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
[        ] #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
[        ] #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[        ] #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
[        ] #11     _StreamController._add (dart:async/stream_controller.dart:648:7)
[        ] #12     _StreamController.add (dart:async/stream_controller.dart:596:5)
[        ] #13     _rootRunUnary (dart:async/zone.dart:1406:47)
[        ] #14     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
[        ] #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
[        ] #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
[        ] #17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[        ] #18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
[        ] #19     _StreamController._add (dart:async/stream_controller.dart:648:7)
[        ] #20     _StreamController.add (dart:async/stream_controller.dart:596:5)
[        ] #21     _Socket._onData (dart:io-patch/socket_patch.dart:2355:41)
[        ] #22     _rootRunUnary (dart:async/zone.dart:1414:13)
[        ] #23     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
[        ] #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
[        ] #25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
[        ] #26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[        ] #27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
[        ] #28     _StreamController._add (dart:async/stream_controller.dart:648:7)
[        ] #29     _StreamController.add (dart:async/stream_controller.dart:596:5)
[        ] #30     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1877:33)
[        ] #31     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1334:14)
[        ] #32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
[        ] #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by git-elliot** [comment]
We run tests in github actions for windows, and all of that are passing. Please check this issue again and reopen if required.
