### ISSUE TITLE
GetIt error 

### ISSUE THREAD

**Issue by guyluz11** [osociety/network_tools#155]
When running `HostScanner.getAllPingableDevices` I am getting the following error

```dart
Unhandled exception:
Bad state: GetIt: Object/factory with type ARPService is not registered inside GetIt. 
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)
#0      throwIfNot (package:get_it/get_it_impl.dart:12:19)
#1      _GetItImplementation._findFactoryByNameAndType (package:get_it/get_it_impl.dart:396:5)
#2      _GetItImplementation.get (package:get_it/get_it_impl.dart:424:29)
#3      _GetItImplementation.call (package:get_it/get_it_impl.dart:464:12)
#4      ActiveHost.arpService (package:network_tools/src/models/active_host.dart:94:35)
#5      ActiveHost.arpService (package:network_tools/src/models/active_host.dart)
#6      ActiveHost.setARPData (package:network_tools/src/models/active_host.dart:186:11)
#7      new ActiveHost (package:network_tools/src/models/active_host.dart:52:15)
#8      new ActiveHost.fromSendableActiveHost (package:network_tools/src/models/active_host.dart:85:12)
#9      HostScanner.getAllPingableDevices (package:network_tools/src/host_scanner.dart:46:37)
<asynchronous suspension>
#10     CompaniesConnectorConjector.searchPingableDevicesAndSetThemUpByHostName (package:cbj_hub/infrastructure/devices/companies_connector_conjector.dart:283:11)
<asynchronous suspension>
```

**Comment by git-elliot** [comment]
Please call configure in main method

https://github.com/osociety/network_tools#for-dart-native

**Comment by guyluz11** [comment]
Greate it solved it.

Should also be added to example files
