### ISSUE TITLE
Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Too many open files, errno = 24), address = , port = 5353

### ISSUE THREAD

**Issue by LiveRock** [osociety/network_tools#163]
Hi

I am getting these in Flutter ios app.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Too many open files, errno = 24), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2558:15)
<asynchronous suspension>
#2      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#3      MdnsScanner.findingMdnsWithAddress (package:network_tools/src/mdns_scanner/mdns_scanner.dart:73:5)
```

How do I resolve it?

**Comment by git-elliot** [comment]
Let's keep only one thread active.
