### ISSUE TITLE
MdnsScannerService.instance.searchMdnsDevices() not working on windows

### ISSUE THREAD

**Issue by git-elliot** [osociety/network_tools#214]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: OS Error: An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call.

, errno = 10042
#0      _NativeSocket.nativeJoinMulticast (dart:io-patch/socket_patch.dart:1799:68)
#1      _NativeSocket.joinMulticast (dart:io-patch/socket_patch.dart:1718:5)
#2      _RawDatagramSocket.joinMulticast (dart:io-patch/socket_patch.dart:2597:13)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:153:16)
<asynchronous suspension>
#4      MdnsScannerServiceImpl.findingMdnsWithAddress (package:network_tools/src/services/impls/mdns_scanner_service_impl.dart:73:5)
<asynchronous suspension>

**Comment by narekpog** [comment]
any updates on this ?
