### ISSUE TITLE
PortScanner.discover The remote computer refused the network connection.

### ISSUE THREAD

**Issue by guyluz11** [osociety/network_tools#23]
I am running this commend 
```dart
  PortScanner.discover(
    target,
    startPort: 8000,
    endPort: 8500,
    timeout: const Duration(milliseconds: 5000),
```
and getting this crash

```dart
Unhandled exception:
SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = 192.168.1.39, port = 64984
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:940:12)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1796:26)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
#4      Socket._connect (dart:io-patch/socket_patch.dart:2019:22)
#5      Socket.connect (dart:io/socket.dart:770:21)
#6      PortScanner.connectToPort (package:network_tools/src/port_scanner.dart:156:37)
#7      PortScanner.customDiscover (package:network_tools/src/port_scanner.dart:87:13)
<asynchronous suspension>
```

If I am changing the duration to `milliseconds: 1000` for example I don't get this crash.

The program should not crash, it should catch the error and continue running on the rest of the ports.

**Comment by git-elliot** [comment]
We can specifically catch the refused connection error and rest of them should be rethrown in my opinion.

**Comment by guyluz11** [comment]
And then suggest the user/programmer to lower amount of requests or duration time

**Comment by git-elliot** [comment]
@guyluz11 Can you please check why this issue still open?

**Comment by guyluz11** [comment]
I looks like it is working now tested on Linux.

Will close it
