### ISSUE TITLE
mdns crash when started in windows connected to WiFi

### ISSUE THREAD

**Issue by guyluz11** [osociety/network_tools#62]
Running mDNS example under windows 10 when connected to WiFi I am getting this error.

```dart
Unhandled exception:
SocketException: Failed to create datagram socket (OS Error: The requested address is not valid in its context.
, errno = 10049), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#2      MdnsScanner._findingMdnsWithAddress (package:network_tools/src/mdns_scanner/mdns_scanner.dart:72:5)
<asynchronous suspension>
```

Cannot reproduce when connected to the network using a cable.

**Comment by git-elliot** [comment]
We run tests in github actions for windows, and all of that are passing. Please check this issue again and reopen if required.
